"""Add notifications table and adjust jurisprudence model

Revision ID: 0752bad12489
Revises: 51246e7e06f7
Create Date: 2025-04-14 18:43:38.199893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0752bad12489'
down_revision: Union[str, None] = '51246e7e06f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jurisprudencia_buscas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('termos_busca', sa.Text(), nullable=False),
    sa.Column('filtros', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('resultados_encontrados', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jurisprudencia_buscas_id'), 'jurisprudencia_buscas', ['id'], unique=False)
    op.create_table('jurisprudencia_resultados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('busca_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('tribunal', sa.String(length=50), nullable=False),
    sa.Column('numero_processo', sa.String(length=100), nullable=True),
    sa.Column('data_julgamento', sa.DateTime(), nullable=True),
    sa.Column('relator', sa.String(length=100), nullable=True),
    sa.Column('ementa', sa.Text(), nullable=False),
    sa.Column('inteiro_teor', sa.Text(), nullable=True),
    sa.Column('url_original', sa.String(length=255), nullable=True),
    sa.Column('relevancia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['busca_id'], ['jurisprudencia_buscas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jurisprudencia_resultados_id'), 'jurisprudencia_resultados', ['id'], unique=False)
    op.drop_index('ix_template_documentos_id', table_name='template_documentos')
    op.drop_table('template_documentos')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('payments')
    op.drop_index('ix_user_notifications_notification_id', table_name='user_notifications')
    op.drop_index('ix_user_notifications_user_id', table_name='user_notifications')
    op.drop_table('user_notifications')
    op.drop_index('ix_planos_id', table_name='planos')
    op.drop_table('planos')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('session_id', sa.VARCHAR(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('role', sa.VARCHAR(), nullable=False),
    sa.Column('tokens_used', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('provider', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('creditos_mensais', sa.INTEGER(), nullable=False),
    sa.Column('preco', sa.FLOAT(), nullable=False),
    sa.Column('recursos', sa.TEXT(), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index('ix_planos_id', 'planos', ['id'], unique=False)
    op.create_table('user_notifications',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('notification_id', sa.VARCHAR(), nullable=False),
    sa.Column('read', sa.BOOLEAN(), nullable=True),
    sa.Column('delivered', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_notifications_user_id', 'user_notifications', ['user_id'], unique=False)
    op.create_index('ix_user_notifications_notification_id', 'user_notifications', ['notification_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('payment_method', sa.VARCHAR(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('card_last_digits', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('target_users', sqlite.JSON(), nullable=True),
    sa.Column('target_role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('target_all', sa.BOOLEAN(), nullable=True),
    sa.Column('expiry_date', sa.DATETIME(), nullable=True),
    sa.Column('action_link', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('created_by', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_table('template_documentos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200), nullable=False),
    sa.Column('categoria', sa.VARCHAR(length=50), nullable=False),
    sa.Column('passos', sa.TEXT(), nullable=False),
    sa.Column('modelo_base', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('destacado', sa.BOOLEAN(), nullable=True),
    sa.Column('contador_uso', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index('ix_template_documentos_id', 'template_documentos', ['id'], unique=False)
    op.drop_index(op.f('ix_jurisprudencia_resultados_id'), table_name='jurisprudencia_resultados')
    op.drop_table('jurisprudencia_resultados')
    op.drop_index(op.f('ix_jurisprudencia_buscas_id'), table_name='jurisprudencia_buscas')
    op.drop_table('jurisprudencia_buscas')
    # ### end Alembic commands ### 