"""Initial migration

Revision ID: 3ed6c639f64b
Revises: 
Create Date: 2025-03-31 14:28:28.926681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = '3ed6c639f64b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('creditos_mensais', sa.Integer(), nullable=False),
    sa.Column('preco', sa.Float(precision=2), nullable=False),
    sa.Column('recursos', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_planos_id'), 'planos', ['id'], unique=False)
    op.create_table('template_documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('passos', sa.Text(), nullable=False),
    sa.Column('modelo_base', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('destacado', sa.Boolean(), nullable=True),
    sa.Column('contador_uso', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_template_documentos_id'), 'template_documentos', ['id'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('premium', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_id'), 'templates', ['id'], unique=False)
    op.create_table('teses_juridicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('area_direito', sa.String(length=100), nullable=False),
    sa.Column('topicos', sa.Text(), nullable=True),
    sa.Column('fundamentos_legais', sa.Text(), nullable=True),
    sa.Column('fonte', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teses_juridicas_id'), 'teses_juridicas', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nome_completo', sa.String(length=255), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('numero_oab', sa.String(length=50), nullable=True),
    sa.Column('estado_oab', sa.String(length=2), nullable=True),
    sa.Column('verificado', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('ultima_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('creditos_disponiveis', sa.Integer(), nullable=True),
    sa.Column('plano', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('documento_gerado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('dados_formulario', sa.Text(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('ultima_modificacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['template_documentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documento_gerado_id'), 'documento_gerado', ['id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('ultima_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('arquivado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.create_table('jurisprudencia_buscas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('termos_busca', sa.Text(), nullable=False),
    sa.Column('filtros', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('resultados_encontrados', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jurisprudencia_buscas_id'), 'jurisprudencia_buscas', ['id'], unique=False)
    op.create_table('sessoes_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('ultima_mensagem', sa.DateTime(), nullable=True),
    sa.Column('arquivado', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessoes_chat_id'), 'sessoes_chat', ['id'], unique=False)
    op.create_table('uso_api',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo_operacao', sa.String(length=100), nullable=False),
    sa.Column('tokens_entrada', sa.Integer(), nullable=False),
    sa.Column('tokens_saida', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('recurso_acessado', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_uso_api_id'), 'uso_api', ['id'], unique=False)
    op.create_table('documento_tese_associacao',
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.Column('tese_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documento_gerado.id'], ),
    sa.ForeignKeyConstraint(['tese_id'], ['teses_juridicas.id'], ),
    sa.PrimaryKeyConstraint('documento_id', 'tese_id')
    )
    op.create_table('jurisprudencia_resultados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('busca_id', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('tribunal', sa.String(length=50), nullable=False),
    sa.Column('numero_processo', sa.String(length=100), nullable=True),
    sa.Column('data_julgamento', sa.DateTime(), nullable=True),
    sa.Column('relator', sa.String(length=100), nullable=True),
    sa.Column('ementa', sa.Text(), nullable=False),
    sa.Column('inteiro_teor', sa.Text(), nullable=True),
    sa.Column('url_original', sa.String(length=255), nullable=True),
    sa.Column('relevancia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['busca_id'], ['jurisprudencia_buscas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jurisprudencia_resultados_id'), 'jurisprudencia_resultados', ['id'], unique=False)
    op.create_table('mensagens_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessao_id', sa.Integer(), nullable=True),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tokens_utilizados', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessoes_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagens_chat_id'), 'mensagens_chat', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mensagens_chat_id'), table_name='mensagens_chat')
    op.drop_table('mensagens_chat')
    op.drop_index(op.f('ix_jurisprudencia_resultados_id'), table_name='jurisprudencia_resultados')
    op.drop_table('jurisprudencia_resultados')
    op.drop_table('documento_tese_associacao')
    op.drop_index(op.f('ix_uso_api_id'), table_name='uso_api')
    op.drop_table('uso_api')
    op.drop_index(op.f('ix_sessoes_chat_id'), table_name='sessoes_chat')
    op.drop_table('sessoes_chat')
    op.drop_index(op.f('ix_jurisprudencia_buscas_id'), table_name='jurisprudencia_buscas')
    op.drop_table('jurisprudencia_buscas')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_documento_gerado_id'), table_name='documento_gerado')
    op.drop_table('documento_gerado')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_teses_juridicas_id'), table_name='teses_juridicas')
    op.drop_table('teses_juridicas')
    op.drop_index(op.f('ix_templates_id'), table_name='templates')
    op.drop_table('templates')
    op.drop_index(op.f('ix_template_documentos_id'), table_name='template_documentos')
    op.drop_table('template_documentos')
    op.drop_index(op.f('ix_planos_id'), table_name='planos')
    op.drop_table('planos')
    # ### end Alembic commands ### 